apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingebox-mw-deployment
  labels:
    app: bingebox-mw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bingebox-mw
  template:
    metadata:
      labels:
        app: bingebox-mw
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: bingebox-mw
          image: 554435745712.dkr.ecr.us-east-1.amazonaws.com/binge-box-mw:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              ephemeral-storage: "500Mi"
              memory: "256Mi"
              cpu: "250m"
            limits:
              ephemeral-storage: "1Gi"
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
